name: MacRDP
on: 
  workflow_dispatch:
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest
    
    steps:                 
    - name: Enabling Remote Access
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
          curl -s -o start.sh -L "https://raw.githubusercontent.com/sajalsoumalya/vps/refs/heads/main/start.sh?token=GHSAT0AAAAAADX32MUOP4FD64D4UIA26FXO2N2G22Q"
          chmod +x start.sh
          bash start.sh "$NGROK_AUTH_TOKEN"
          
    - name: Log In Details To VNC Server
      run: |
         chmod +x login.sh
         bash login.sh
         
    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
