name: Setup Versu Mining on macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Homebrew packages
      run: |
        brew update
        brew install cmake boost

    - name: Clone nheqminer (or Versu fork)
      run: |
        git clone https://github.com/nicehash/nheqminer.git
        cd nheqminer
        mkdir build
        cd build
        cmake -DBOOST_ROOT=/opt/homebrew/opt/boost ..
        make -j$(sysctl -n hw.ncpu)

    - name: Verify nheqminer version
      run: |
        cd nheqminer/build
        ./nheqminer -v || echo "Build succeeded but miner cannot run in GitHub Actions"
